# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b12ad8a87fb5129971cad9758f44a58ac63f39f07a40d538ea8c21e5b19104a521e9fb56b6773b8ca9b16d6a642f22d148c2533b035846f8f1ed4038e0e8a201

test:
  secret_key_base: 20752196eabcb9a39a15e2416f916fd135a3ab6636fa9291682b6956522a005f1d52b77750b3bf4053172ed098c95598cdeed9b7d77d25b190a4c9d21dc2d1db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
